wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.46.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737653325
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      - 105
      3:
      - 23
      4: 3.10.14
      5: 0.17.1
      6: 4.46.2
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.001
